### PR TITLE
Pull request 3

### PR DESCRIPTION
**Pull request by lauw26**
Card object constructor implemented.
Create deck function created to create and store 52 unique card objects.
Player object constructor implemented.
Create player function creates player and dealer and stores them in an array.
Draw function draws 2 cards.
Card draw function draws a card and check if it already been dealt before returning the card

### CODE REVIEW

**Comment by richgurney** [comment]
Hi Will, whats the state of your game?

**Comment by lauw26** [comment]
The card,deck and player object have been implemented. I am able to draw 2 unique cards and store them in the player and dealer's hands.

**Comment by lauw26** [comment]
currently working on the total functions to add up their hands

**Comment by richgurney** [comment]
Ok brill. Let me know when your happy that is a game and is ready for review

**Comment by richgurney** [comment]
Im going to close this pull request so when your ready do another one

**Pull request closed without merging**
